### PR TITLE
feat: add ci workflows for operator

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>

### CODE REVIEW

**Comment by kushthedude** [comment]
@leecalcote CI has been established now there are few outstanding errors in operator which @kalradev may look into 🙂

**Comment by leecalcote** [comment]
We will need a Docker build and push section for the MeshSync container.  

We will need edge and stable release channels.

**Comment by leecalcote** [comment]
Meshery-operator repo - https://hub.docker.com/r/layer5/meshery-operator

**Comment by kushthedude** [comment]
@leecalcote Docker build cant be done until the operator is fixed, so first the build step needs to succed before I can write docker job or else there will be no way to test if the docker job written is even working or not.

**Comment by kushthedude** [comment]
Ready to be merged @leecalcote

**Review by leecalcote — APPROVED** [review]
LGTM

**Pull request merged**
