### PR TITLE
changed GO mod project name to meshery-operator

### PR DESCRIPTION
**Pull request by crustyy**
Signed-off-by: crustyy <muskanbansal919@gmail.com>

### CODE REVIEW

**Comment by nitishm** [comment]
@leecalcote I need write access to this repo to merge PRs 😄

**Comment by nitishm** [comment]
Fixes #9 and #13

**Comment by leecalcote** [comment]
Waaaait a second... are you saying @crustyy delivered a double-header in this PR?

I like it!

**Comment by leecalcote** [comment]
@crustyy there's a neat little trick that @nitishm is quietly pointing out here. From Meshery's [CONTRIBUTING.md](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#contributing-overview):

> All pull requests should reference an open issue. Include keywords in your pull request descriptions, as well as commit messages, to [automatically close issues in GitHub](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords).

**Pull request merged**
