### PR TITLE
[WIP] Add models and interfaces for meshsync

### PR DESCRIPTION
**Pull request by nitishm**
Created and implemented interfaces and models for meshsync to be used across meshes

Signed-off-by: Nitish Malhotra <nitish.malhotra@gmail.com>

### CODE REVIEW

**Comment by nitishm** [comment]
Tried to abstract a few things:
- A meshsync specific `MeshInfo` object that serves as a common abstraction across all meshes, by which I mean that every mesh should finally be adapted to his meshery-operator native object and it's fields.
- An `Info()` interface which must be implemented by every mesh.

@leecalcote @AdheipSingh @vinayakshnd @kushthedude

**Comment by leecalcote** [comment]
A couple conflicts in go.mod and go.sum to have a peek at.

**Comment by leecalcote** [comment]
I get the following error when building the project:

```
✗ make clean
rm -rf bin
go mod tidy
go: meshery-operator/pkg/meshsync/istio imports
        istio.io/istio/pkg/kube imports
        k8s.io/kubectl/pkg/cmd/apply imports
        k8s.io/kubectl/pkg/cmd/util/editor imports
        k8s.io/kubectl/pkg/util/term imports
        github.com/docker/docker/pkg/term imports
        github.com/docker/docker/pkg/term/windows imports
        github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.6.0: parsing go.mod:
        module declares its path as: github.com/sirupsen/logrus
                but was required as: github.com/Sirupsen/logrus
make: *** [clean] Error 1
```

**Comment by nitishm** [comment]
> I get the following error when building the project:
> 
> ```
> ✗ make clean
> rm -rf bin
> go mod tidy
> go: meshery-operator/pkg/meshsync/istio imports
>         istio.io/istio/pkg/kube imports
>         k8s.io/kubectl/pkg/cmd/apply imports
>         k8s.io/kubectl/pkg/cmd/util/editor imports
>         k8s.io/kubectl/pkg/util/term imports
>         github.com/docker/docker/pkg/term imports
>         github.com/docker/docker/pkg/term/windows imports
>         github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.6.0: parsing go.mod:
>         module declares its path as: github.com/sirupsen/logrus
>                 but was required as: github.com/Sirupsen/logrus
> make: *** [clean] Error 1
> ```

Can you delete go.mod and go.sum and retry? I didnt use the `Makefile` so I mightve missed something. Will give it try later today.

**Comment by leecalcote** [comment]
You got it. I deleted `go.mod` and `go.sum`. Rerunning `make` produces the same error. However, running `go build cmd/meshsync/main.go` successfully builds.

**Pull request merged**
