### PR TITLE
Updated README community section

### LINKED ISSUE #161: [README] Update README Community Section
**Description**
The Community section in the README says "Access the Community Drive". There is a new procedure of having this automated based on the individual filling in a [community member form](https://layer5.io/newcomer)

**Expected Behavior**
Update "Access Community Drive" to "To Access Community Drive, fill Community Member Form"

**Screenshots**
img
--

**Resources**
Refer to the [Contributing guide](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#contributing)

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

### PR DESCRIPTION
**Pull request by Evavic44**
**Description**
Updated README community section and added the required text.

This PR fixes 
#161 

**Notes for Reviewers**
I also added the link of the `Community member form` with this [link](https://layer5.io/newcomer) provided in the issues section.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Abiola-Farounbi** [comment]
Hi @Evavic44 ,
some of the checks were not successful, to contribute to this project, you must agree to the Developer Certificate of Origin (DCO) for each commit you make, that is you would have to Sign-off on Commits ; using

` git commit --signoff -m'<commit subject>' `

**Review by Abiola-Farounbi — COMMENTED** [review]
Hi @Evavic44,
some of the checks were not successful, to contribute to this project, you must agree to the Developer Certificate of Origin (DCO) for each commit you make, that is you would have to Sign-off on Commits; using

` git commit --signoff -m'<commit subject>' `

**Review by Anita-ihuman — COMMENTED** [review]
Thank you for picking this issue @Evavic44.
Please remove the google drive link from "Community drive" and leave it as just text.
Include a full stop (.)at the end of the text.

**Comment by Evavic44** [comment]
> git commit --signoff -m'<commit subject>'

Oh, sorry about that. Will sign it this time

**Comment by Evavic44** [comment]
> Thank you for picking this issue @Evavic44.
> Please remove the google drive link from "Community drive" and leave it as just text.
> Include a full stop (.)at the end of the text.

I've updated it with the requested changes. 👍🏾

**Comment by Abiola-Farounbi** [comment]
> 
> 
> > git commit --signoff -m''
> 
> Oh, sorry about that. Will sign it this time
> I tried the above command but it still couldn't sign off the commits. Is there something I'm doing wrong?

Try using this exact command
`git commit --signoff -m'Updated README community section '`

**Comment by Evavic44** [comment]
> > > git commit --signoff -m''
> > 
> > 
> > Oh, sorry about that. Will sign it this time
> > I tried the above command but it still couldn't sign off the commits. Is there something I'm doing wrong?
> 
> Try using this exact command
> `git commit --signoff -m'Updated README community section '`

Done

**Comment by Anita-ihuman** [comment]
> > > > git commit --signoff -m''
> > > 
> > > 
> > > Oh, sorry about that. Will sign it this time
> > > I tried the above command but it still couldn't sign off the commits. Is there something I'm doing wrong?
> > 
> > 
> > Try using this exact command
> > `git commit --signoff -m'Updated README community section '`
> 
> Done

**Review by Anita-ihuman — COMMENTED** [review]
Please Remove the Google drive link from the "Community Drive", we do not need it again in the text.
Then when you are about to write your commit message in the terminal,  you indicate the sign off

`git commit -s -m " your commit message"`

Like so.

**Comment by Evavic44** [comment]
> Please Remove the Google drive link from the "Community Drive", we do not need it again in the text.
> Then when you are about to write your commit message in the terminal, you indicate the sign off
> 
> `git commit -s -m " your commit message"`
> 
> Like so.

I used the command provided and pushed it. Here's a preview. Is this the sign-off you're asking about. Also, I've already removed the google drive link. [Here](https://github.com/layer5io/meshery-operator/pull/162/commits/0fbf4b5c2813d0f6d59341b13296425118637d15)
Annotation 2021-05-19 112039

**Comment by Anita-ihuman** [comment]
Run these commands in the terminal. https://github.com/layer5io/meshery-operator/pull/162/checks?check_run_id=2618292683

**Comment by Evavic44** [comment]
> Run these commands in the terminal. https://github.com/layer5io/meshery-operator/pull/162/checks?check_run_id=2618292683

I did and this is what I got. 
Annotation 2021-05-20 013829
So sorry for wasting your time, would it be better to close this issue, so I can create a new PR but this time signing the commits? Or is there a better way to solve this?

**Review by leecalcote — APPROVED** [review]
@Evavic44 DCO has been more of a pain here than it needs to be. Let's get you commit manually signed off and your PR on its way. 🙂 

Thanks for knocking this issue out, @Evavic44 👍

**Comment by Evavic44** [comment]
> @Evavic44 DCO has been more of a pain here than it needs to be. Let's get you commit manually signed off and your PR on its way. 🙂 
> 
> Thanks for knocking this issue out, @Evavic44 👍 

Lol. Thank you 😊 this is my first experience with DCO. Would research more about it.

**Comment by leecalcote** [comment]
Fortunately, it is generally (but not always), it is one of those things that after you’ve taken care of it once, you can almost forget about it. Here is more background on it and a couple of suggested approaches to making sign offs implicit to all of your commits - https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin

**Pull request merged**
